# -*- coding: utf-8 -*-
"""2026-09-18 sheet import: diff the 18-09 exports against the live DB and write ONE transactional
SQL file (sql_0918.sql). Insert-only for new rows (Ben's rule since 2026-08-26 - staff edit existing
rows through the web app), plus one backfill: main_7_last_match.last_match_price where the DB is NULL.

Inputs (dumped by psql into the session scratchpad, see the session log):
  db.json      - current PKs / keys of the target tables + activities tuples
  lookups.json - live lookup table values (validation uses these, NOT hardcoded sets)
Usage: python build_0918.py <dir-with-db.json-and-lookups.json>
"""
import csv, io, os, re, sys, json
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1]
DB = json.load(io.open(os.path.join(SRC, "db.json"), encoding="utf-8"))
LK = json.load(io.open(os.path.join(SRC, "lookups.json"), encoding="utf-8"))

report = io.open(os.path.join(HERE, "build_0918_report.txt"), "w", encoding="utf-8")
def rp(*a):
    line = " ".join(str(x) for x in a)
    sys.stdout.buffer.write((line + "\n").encode("utf-8"))
    report.write(line + "\n")

def load(name):
    with io.open(os.path.join(HERE, "18-09" + name), encoding="utf-8-sig", newline="") as fh:
        return list(csv.reader(fh))

def s(v):
    v = (v or "").strip()
    return v or None

def date(v):
    m = re.fullmatch(r"(\d{1,2})/(\d{1,2})/(\d{4})", (v or "").strip())
    if not m: return None
    d, mo, y = map(int, m.groups())
    if y > 2400: y -= 543
    if y < 2000 or not (1 <= mo <= 12 and 1 <= d <= 31): return None   # 30/12/1899 = empty cell
    return "%04d-%02d-%02d" % (y, mo, d)

def num(v):
    # the 08-03 import lost every Last Match price because "฿3,600,000" failed this parse
    v = (v or "").replace(",", "").replace("฿", "").strip()
    if not v or v == "-": return None
    return float(v) if re.fullmatch(r"-?\d+(\.\d+)?", v) else None

def integer(v):
    n = num(v)
    return int(n) if n is not None else None

def boolean(v):
    v = (v or "").strip().upper()
    return True if v == "TRUE" else (False if v == "FALSE" else None)

def link(v):
    v = (v or "").strip()
    return None if not v or v.upper() in ("TRUE", "FALSE") else v

def lit(v):
    if v is None: return "NULL"
    if isinstance(v, bool): return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)): return repr(v)
    return "'" + str(v).replace("'", "''") + "'"

def only(v, table):
    return v if v in set(LK[table]) else None

NICK = {h["nick"]: h["code"] for h in LK["hr"]}
NICK.update({"Stone Bangyai": "C-001", "Stone+Pup": "C-001"})
def emp(v):
    return NICK.get((v or "").strip())

ZONE = {}
for z in LK["zone"]:
    for k in (z["name_eng"], z["name_thai"]):
        if k and k != "Out of zone" and k != "นอกโซน":
            ZONE[k.strip()] = z["zone_id"]
ZONE.update({"Don Mueang": "DMK", "Ngamwongwan": "NGM", "Ratchaphruek (ต้น)": "RP1"})
def zone(v):
    return ZONE.get((v or "").strip())

def insert(table, rows):
    cols = list(rows[0].keys())
    vals = ",\n".join("  (%s)" % ", ".join(r[c] if isinstance(r[c], Raw) else lit(r[c]) for c in cols) for r in rows)
    return "insert into %s (%s) values\n%s;\n" % (table, ", ".join(cols), vals)

class Raw(str):
    """A value written into the SQL verbatim (a subselect)."""

out = ["-- generated by import/build_0918.py - one transaction, insert-only + last_match_price backfill",
       "begin;",
       "-- bulk leads must not fire one notification each (CLAUDE.md)",
       "alter table main_6_buyer_crm disable trigger trg_notify_lead_assigned;"]

# ================= 1) PROJECTS (match by Thai name only - sheet Project ID drifts) =================
rows = load("Database Sheets - Project.csv"); H = [h.strip() for h in rows[0]]
hi = {h: i for i, h in enumerate(H)}
G = lambda r, n: r[hi[n]] if hi.get(n) is not None and hi[n] < len(r) else ""
db_thai = {}
for p in DB["projects"]:
    db_thai.setdefault(p["th"], p["id"])
next_pid = max(int(re.search(r"\d+$", p["id"]).group()) for p in DB["projects"]) + 1
new_projects, thai2pid = [], dict(db_thai)
for r in rows[1:]:
    if not s(G(r, "Project ID")): continue
    th = s(G(r, "Project Name (Thai)"))
    if not th or th in thai2pid: continue
    pid = "PROJECT-%03d" % next_pid; next_pid += 1
    thai2pid[th] = pid
    new_projects.append({
        "project_id": pid,
        "project_name_eng": s(G(r, "Project Name (Eng)")),
        "project_name_thai": th,
        "property_type": only(s(G(r, "Property Type")), "property_type"),
        "zone": zone(G(r, "Zone")),
        "total_units": integer(G(r, "จำนวนยูนิต")),
        "phases": integer(G(r, "กี่เฟส")),
        "unit_types": s(G(r, "ประเภท Type ยูนิต")),
        "material": s(G(r, "วัสดุ")),
        "floor_to_ceiling": s(G(r, "Floor to c")),
        "project_age": s(G(r, "อายุโครงการ")),
        "facilities": s(G(r, "ส่วนกลาง")),
        "common_fee": num(G(r, "ค่าส่วนกลาง")),
        "juristic": s(G(r, "นิติบุคคล")),
        "juristic_collect_pct": num(G(r, "นิติเก็บค่าส่วนกลางได้กี่ %")),
        "extra_parking_fee": num(G(r, "จอดเกินต้องเสียคันละเท่าไหร ?")),
        "rental_price_in_project": s(G(r, "ราคาปล่อยเช่าในโครงการ")),
        "flooding": boolean(G(r, "น้ำท่วมขังหรือไม่ ?")),
        "resident_occupation": s(G(r, "อาชีพลูกบ้าน")),
        "project_sold_price": s(G(r, "ราคาจบโครงการ")),
        "pros": s(G(r, "ข้อดี")),
        "cons": s(G(r, "ข้อเสีย")),
        "sales_id": emp(G(r, "Sales Created By")),
        "date_created": date(G(r, "Date Created")),
    })
rp("PROJECTS new:", len(new_projects))
for p in new_projects:
    rp("   ", p["project_id"], p["project_name_thai"], p["zone"], p["property_type"])
if new_projects:
    out.append("-- projects"); out.append(insert("main_3_property_detail", new_projects))

# ================= 2) OWNERS + LISTINGS =================
rows = load("Database Sheets - All Listings.csv"); H = [h.strip() for h in rows[0]]
# The 18-09 export has an extra, always-empty DATA column right after "Bath" that the header row does
# not have: every value from ไร่ onward sits one cell to the right of its header (and the last column,
# Marketing Report, falls off the end). Verified against the 08-26 export row by row. Re-align, and
# refuse to run if the shape ever differs so a fixed export is not shifted the other way.
bath = H.index("Bath")
assert all(len(r) == len(H) and not r[bath + 1].strip() for r in rows[1:]), "listing export shape changed"
assert sum(1 for r in rows[1:] if r[H.index("Created By") + 1].strip() in NICK) > 500, "shift not where expected"
H = H[:bath + 1] + ["(blank)"] + H[bath + 1:-1]
hi = {h: i for i, h in enumerate(H)}
C = lambda r, n: r[hi[n]] if hi.get(n) is not None and hi[n] < len(r) else ""
OWN_PHONE = [h for h in H if h.startswith("Owner's Phone")][0]
OWN_LINE = [h for h in H if h.startswith("Owner's LINE")][0]
db_listing = {x["id"] for x in DB["listings"]}
targets, seen = [], set()
for r in rows[1:]:
    lid = s(C(r, "Listing ID"))
    if lid and lid not in db_listing and lid not in seen:
        seen.add(lid); targets.append(r)

owner_keys, owner_vals = set(), []
for r in targets:
    n, p = s(C(r, "Owner's Name")), s(C(r, OWN_PHONE))
    if n and (n, p) not in owner_keys:
        owner_keys.add((n, p))
        owner_vals.append("(%s, %s, %s)" % (lit(n), lit(p), lit(s(C(r, OWN_LINE)))))
if owner_vals:
    out.append("-- owners (only those not already in main_2_owner by name+phone)")
    out.append("insert into main_2_owner (owner_name, owner_phone, owner_line)\n"
               "select v.name, v.phone, v.line from (values\n  " + ",\n  ".join(owner_vals) + "\n) as v(name, phone, line)\n"
               "where not exists (select 1 from main_2_owner o where o.owner_name = v.name\n"
               "  and o.owner_phone is not distinct from v.phone);\n")

listings, no_project = [], []
for r in targets:
    lid = s(C(r, "Listing ID"))
    th = s(C(r, "Project Name (Eng)"))   # sheet keeps the THAI name in this column
    own_name, own_phone = s(C(r, "Owner's Name")), s(C(r, OWN_PHONE))
    row = {
        "listing_id": lid, "date_created": date(C(r, "Date")), "project_id": thai2pid.get(th),
        "listing_status": only(s(C(r, "Listing Status")), "listing_status"),
        "potential": only(s(C(r, "Potential")), "listing_potential"),
        "sign": boolean(C(r, "Sign")), "vdo": boolean(C(r, "VDO")),
        "ddproperty_link": link(C(r, "Ddproperty Link")),
        "livinginsider_link": link(C(r, "Livinginsider Link")),
        "propertyhub_link": link(C(r, "Facebook Link")),
        "old_price": num(C(r, "Old Price")), "new_price": num(C(r, "New Price")),
        "update_remark": s(C(r, "Update Remark")),
        "last_match_price": num(C(r, "Last Match\nPrice")),
        "last_match_remark": s(C(r, "Last Match Remark")),
        "buyer_persona": s(C(r, "Buyer Persona")), "hook": s(C(r, "Buyer Persona")),
        "owner_focus": boolean(C(r, "Owner Focus")),
        "listing_type": only(s(C(r, "Listing Type")), "listing_type"),
        "unit_no": s(C(r, "Unit no.")),
        "owner_talk_last_date": date(C(r, "วันที่ Owner Talk ล่าสุด")),
        "activity_comment": s(C(r, "Activity Comment")),
        "property_type": only(s(C(r, "Property Type")), "property_type"),
        "in_out_project": only(s(C(r, "ใน/นอกโครงการ")), "in_out_project"),
        "road_soi": s(C(r, "ชื่อถนน/ซอย")), "zone": zone(C(r, "Zone")),
        "bed": integer(C(r, "Bed")), "bath": num(C(r, "Bath")),
        "area_rai": num(C(r, "ไร่")), "area_ngan": num(C(r, "งาน")),
        "area_wa": num(C(r, "วา")), "area_sqm": num(C(r, "ตรม. / ใช้สอย")),
        "floor": s(C(r, "ชั้น")),
        # columns the sheet fills shifted -> keep only values that are valid for the column (Ben, 08-03)
        "direction": only(s(C(r, "ทิศ")), "direction"),
        "unit_position": only(s(C(r, "ตำแหน่ง")), "unit_position"),
        "built_year": None,
        "parking": integer(C(r, "Parking")),
        "asking_price": num(C(r, "Asking Price")), "rental_price": num(C(r, "Rental Price")),
        "price_remark": only(s(C(r, "Price Remark")), "price_remark"),
        "remark": s(C(r, "Remark")),
        "photo_album_link": link(C(r, "Photo Album Link")),
        "link_location": link(C(r, "Link Location")),
        "unit_condition": only(s(C(r, "Unit Condition")), "unit_condition"),
        "last_match": s(C(r, "Last Match")),
        "last_match_type": only(s(C(r, "Last Match Type")), "close_type"),
        "sale_id": emp(C(r, "Created By")),
        "marketing_report": link(C(r, "Marketing Report")),
        "dd_boost": boolean(C(r, "DD Boost")), "lv_boost": boolean(C(r, "LV Boost")),
        "fb_repost": boolean(C(r, "FB Repost")),
        "new_photo_link": link(C(r, "New Photo\n(Link)")),
        "shorts_reels_link": link(C(r, "Shorts / Reels\n(Link)")),
        "hometour_link": link(C(r, "Hometour\n(Link)")),
        "facebook_ad_link": link(C(r, "Facebook Ad\n(Google Doc Link)")),
        "common_fee_note": None, "common_fee_rate": None, "common_fee_unit": None,
        "owner_id": Raw("(select owner_id from main_2_owner where owner_name = %s and owner_phone %s order by owner_id desc limit 1)"
                        % (lit(own_name), ("= " + lit(own_phone)) if own_phone else "is null")) if own_name else None,
    }
    m = re.fullmatch(r"(\d+)\s*ปี\s*", (C(r, "อายุ") or "").strip())
    if m and row["date_created"]:
        row["built_year"] = int(row["date_created"][:4]) - int(m.group(1))
    fee = (C(r, "ส่วนกลาง") or "").strip()
    if fee and ("บาท" in fee or re.fullmatch(r"[\d,\.]+", fee)):
        row["common_fee_note"] = fee
        mm = re.search(r"([\d,\.]+)", fee)
        if mm and "บาท" in fee:
            row["common_fee_rate"] = num(mm.group(1)); row["common_fee_unit"] = "per_wa_month"
    if not row["project_id"]: no_project.append((lid, th))
    listings.append(row)
rp("\nLISTINGS new:", len(listings), " owners candidate:", len(owner_vals))
for x in listings:
    rp("   ", x["listing_id"], x["project_id"], x["zone"], x["listing_status"], x["potential"], x["sale_id"], x["asking_price"])
rp("listings without a project match:", no_project)
if listings:
    out.append("-- listings"); out.append(insert("main_4_listing_database", listings))
all_listing_ids = db_listing | {x["listing_id"] for x in listings}

# ================= 3) LEADS (Active Lead; cols 2-7 are shifted one to the left of their headers) =================
rows = load("Database Sheets - Active Lead.csv"); H = [h.strip() for h in rows[0]]
hi = {h: i for i, h in enumerate(H)}
db_lead = {x["id"] for x in DB["leads"]}
def base(i):
    m = re.match(r"^(L\d\d-\d+)(-\d+)?$", i); return m.group(1) if m else i
db_base = {base(i) for i in db_lead}
leads, used, skipped_leads, bad_listing = [], set(), [], []
for r in rows[1:]:
    g = lambda n: r[hi[n]] if hi.get(n) is not None and hi[n] < len(r) else ""
    lead_id = s(g("Lead ID"))
    if not lead_id or lead_id in db_base: continue
    if not re.fullmatch(r"L\d\d-\d+", lead_id):
        skipped_leads.append(lead_id); continue           # LEAD-01 = Ben's test rows (BEN001)
    lid, k = lead_id, 1
    while lid in used:                                       # same id reused for a different person
        k += 1; lid = "%s-%d" % (lead_id, k)
    used.add(lid)
    code = s(g("Listing Code"))
    if code and code not in all_listing_ids:
        bad_listing.append((lid, code)); code = None
    leads.append({
        "lead_id": lid, "date_received": date(g("Date Received")), "listing_code": code,
        "potential": only(s(r[2]), "potential"), "lead_status": only(s(r[3]), "lead_status"),
        "interested": s(r[4]), "lead_name": s(r[5]), "phone": s(r[6]), "admin_remark": s(r[7]),
        "line_id": s(g("LINE ID")), "budget": num(g("Budget")),
        "pipeline_stage": only(s(g("Pipeline Stage")), "pipeline_stage"),
        "last_follow_date": date(g("วันที่ Follow ล่าสุด")),
        "activity_comment": s(g("Activity Comment")), "commission": num(g("Commission")),
        "closing_date": date(g("Closing Date")), "transfer_date": date(g("Transfer Date")),
        "case_closing_remark": s(g("Case Closing Remark")),
        "complete": boolean(g("Complete")), "confirm": boolean(g("Confirm")),
        "sale_id": emp(g("Created By")), "lead_type": only(s(g("Lead Type")), "lead_type"),
    })
rp("\nLEADS new rows:", len(leads), " suffixed:", [x["lead_id"] for x in leads if x["lead_id"].count("-") > 1])
rp("leads skipped (not an L26 id):", sorted(set(skipped_leads)), " listing_code not found -> NULL:", bad_listing)
rp("leads without sale_id:", [x["lead_id"] for x in leads if not x["sale_id"]])
if leads:
    out.append("-- leads"); out.append(insert("main_6_buyer_crm", leads))

# ================= 4) LAST MATCH =================
rows = load("Database Sheets - Last Match.csv"); H = [h.strip() for h in rows[0]]
hi = {h: i for i, h in enumerate(H)}
db_lm = {x["last_match_id"]: x for x in DB["lastmatch"]}
new_lm, backfill, lm_skipped, seen = [], [], Counter(), set()
for r in rows[1:]:
    g = lambda n: r[hi[n]] if hi.get(n) is not None and hi[n] < len(r) else ""
    mid = s(g("Last Match ID"))
    if not mid or not re.fullmatch(r"[A-Za-z+]+-\d+", mid):   # blank, or a pasted URL (shifted row)
        lm_skipped["no/bad id"] += 1; continue
    price = num(g("Last Match Price"))
    if mid in db_lm:
        if db_lm[mid]["last_match_price"] is None and price is not None:
            backfill.append((mid, price))
        continue
    prefix = mid.rsplit("-", 1)[0]
    sale = emp(g("By")) or emp(prefix)                        # Q-17..19 have a blank "By"
    if prefix == "Test" or not sale: lm_skipped["test/unknown seller"] += 1; continue
    if mid in seen: lm_skipped["dup id"] += 1; continue
    seen.add(mid)
    sq, bb = g("Sq.wa / Sq.m"), g("Bed/Bath")
    bbm = re.fullmatch(r"\s*(\d+)\s*/\s*(\d+(?:\.\d+)?)\s*", bb or "")
    new_lm.append({
        "last_match_id": mid, "sale_id": sale,
        "close_type": only(s(g("Type")), "close_type"),
        "project_name": s(g("Projects Name")),
        "property_type": only(s(g("Property Type")), "property_type"),
        "zone": zone(g("Zone")),
        "sq_wa": num((sq or "").split("/")[0]),
        "sq_m": num(sq.split("/")[1]) if "/" in (sq or "") else None,
        "bed": int(bbm.group(1)) if bbm else None,
        "bath": float(bbm.group(2)) if bbm else None,
        "last_match_price": price,
        "last_match_remark": s(g("Last Match Remark")),
        "buyer_persona": s(g("Buyer Persona")),
        "date_created": date(g("Date Created")),
    })
rp("\nLAST MATCH new:", [(x["last_match_id"], x["sale_id"], x["last_match_price"]) for x in new_lm])
rp("last match skipped:", dict(lm_skipped))
rp("last_match_price backfill (DB NULL -> sheet value):", len(backfill), "of", len(db_lm))
if new_lm:
    out.append("-- last match"); out.append(insert("main_7_last_match", new_lm))
if backfill:
    out.append("-- backfill prices the 08-03 import dropped (฿ prefix broke the number parse); only where still NULL")
    out.append("update main_7_last_match m set last_match_price = v.price from (values\n  " +
               ",\n  ".join("(%s, %s)" % (lit(i), lit(p)) for i, p in backfill) +
               "\n) as v(id, price) where m.last_match_id = v.id and m.last_match_price is null;\n")

# ================= 5) ACTIVITIES (no natural key -> grouped tuple diff) =================
ACTS = set(LK["action_type"])
ALIAS = {"Visit": "Owner Visit", "Showing": "Show", "Closing": "Close", "อื่นๆ (ระบุ Remark)": "อื่นๆ",
         "ถ่าย": "ถ่ายรูป", "เปลี่ยนน้ำ,ไฟ": "อื่นๆ", "ทิศเหนือ": "อื่นๆ", "แจ้งวัฒนะ": "อื่นๆ", "รีวิวจาก": "อื่นๆ",
         "Reel": "Reels", "Viait": "Owner Visit"}   # typos seen in the 18-09 export
rows = load("Database Sheets - Action.csv"); H = [h.strip() for h in rows[0]]
hi = {h: i for i, h in enumerate(H)}
csvc, skip = Counter(), Counter()
for r in rows[1:]:
    g = lambda n: r[hi[n]] if hi.get(n) is not None and hi[n] < len(r) else ""
    d, who = date(g("Date")), emp(g("Sale Name"))
    a = s(g("Action")); a = ALIAS.get(a, a)
    if not (d and who and a in ACTS):
        skip[(s(g("Sale Name")), a, d)] += 1; continue
    csvc[(who, a, d, max(1, integer(g("จำนวน")) or 1))] += 1
dbc = Counter((x["e"], x["a"], x["d"], x["c"]) for x in DB["acts"] if x["task"] is None)
miss = [k for k, v in sorted(csvc.items()) for _ in range(v - dbc[k]) if v > dbc[k]]
rp("\nACTIVITIES insert:", len(miss), " by month:", sorted(Counter(k[2][:7] for k in miss).items()),
   " by person:", sorted(Counter(k[0] for k in miss).items()))
rp("activities skipped since 2026-08 (bad action text):", [k for k in skip if k[2] and k[2] >= "2026-08"])
if miss:
    out.append("-- activities")
    out.append(insert("activities", [{"employee_code": w, "action": a, "activity_date": d, "count": c} for w, a, d, c in miss]))

out.append("alter table main_6_buyer_crm enable trigger trg_notify_lead_assigned;")
out.append("commit;")
io.open(os.path.join(SRC, "sql_0918.sql"), "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
rp("\nWROTE sql_0918.sql")
report.close()
